# Generated by Django 3.1.2 on 2021-08-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('curr_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
