# Generated by Django 3.1.2 on 2021-08-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_transactions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='receiver_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sender_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
