# Generated by Django 3.1.2 on 2021-08-12 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210813_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='sender_name',
        ),
    ]
