# Generated by Django 3.1.2 on 2021-08-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210813_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='reveiver_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sender_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
