# Generated by Django 3.1.2 on 2021-08-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210813_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='reveiver_name',
            new_name='receiver_name',
        ),
    ]
